# Generated by Django 5.2.5 on 2025-10-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('address_street_number', models.TextField()),
                ('address_street_name', models.TextField()),
                ('address_apartment_number', models.TextField()),
                ('address_zip_code', models.IntegerField()),
                ('date_of_birth', models.DateTimeField()),
                ('registration_date', models.DateTimeField()),
                ('party_affiliation', models.TextField()),
                ('precint_number', models.IntegerField()),
                ('v20state', models.BooleanField()),
                ('v21town', models.BooleanField()),
                ('v21primary', models.BooleanField()),
                ('v22general', models.BooleanField()),
                ('v23town', models.BooleanField()),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
