# Generated by Django 5.2.5 on 2025-10-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0003_alter_voter_date_of_birth_alter_voter_precint_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
