# Generated by Django 5.2.5 on 2025-10-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0002_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_field',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
