# Generated by Django 5.2.5 on 2025-10-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0003_photo_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
