# Generated by Django 5.2.5 on 2025-10-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0004_profile_profile_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image_field',
            new_name='profile_image_file',
        ),
    ]
