# Generated by Django 5.2.5 on 2025-10-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0005_rename_image_field_photo_profile_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='profile_image_file',
            new_name='image_file',
        ),
    ]
