# Generated by Django 5.2.5 on 2025-10-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
