# Generated by Django 5.2.5 on 2025-10-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
    ]
