# Generated by Django 5.2.5 on 2025-11-22 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(blank=True)),
                ('lastName', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(blank=True)),
                ('lastName', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(blank=True)),
                ('lastName', models.TextField(blank=True)),
                ('middleName', models.TextField(blank=True)),
                ('DOB', models.DateField()),
                ('primaryCareDoctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('problem', models.TextField()),
                ('problemDescription', models.TextField()),
                ('appointmentType', models.CharField()),
                ('headDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_appointments_doctor', to='project.doctor')),
                ('otherDoctors', models.ManyToManyField(blank=True, related_name='other_appointments_doctor', to='project.doctor')),
                ('headNurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_appointments_nurse', to='project.nurse')),
                ('otherNurses', models.ManyToManyField(blank=True, related_name='other_appointments_nurse', to='project.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.patient')),
            ],
        ),
    ]
