# Generated by Django 5.2.5 on 2025-11-25 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='headDoctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='headNurse',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='otherDoctors',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='otherNurses',
        ),
        migrations.CreateModel(
            name='DoctorProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.appointment')),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='NurseProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.appointment')),
                ('nurseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.nurse')),
            ],
        ),
    ]
