# Generated by Django 5.2.5 on 2025-11-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_patient_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.TextField(blank=True),
        ),
    ]
