# Generated by Django 5.2.5 on 2025-11-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
