# Generated by Django 5.2.5 on 2025-11-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_patient_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='nurse',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
