# Generated by Django 5.2.5 on 2025-11-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_doctor_picture_nurse_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentType',
            field=models.CharField(choices=[('CU', 'Checkup'), ('PO', 'Post Operation'), ('SP', 'Specialist Consultation'), ('FU', 'Follow-up Visit'), ('NA', 'Nurse Appointment'), ('PE', 'Pre-operation Visit'), ('CO', 'Counselling Session'), ('TH', 'Telehealth/Virtual Visit'), ('VA', 'Vaccination Appointment'), ('A', 'Annual Checkup'), ('BC', 'Birth Control Consultation'), ('MC', 'Medication Check')], max_length=2),
        ),
    ]
